db "DATE:",			COMPILING_DATE ,	10
db "TIME:",			COMPILING_TIME,		10
db "NASM_VERSION:",		__NASM_VER__ , 		10
db "COMPILING_MACHINE:",	COMPILING_MACHINE, 	10
db "COMPILING_OS:",		COMPILING_OS, 		10
db "COMPILING_HOST:",		COMPILING_HOST,		10
db 0