db "DATE:",			COMPILING_DATE ,	32
db "TIME:",			COMPILING_TIME,		32
db "NASM_VERSION:",		__NASM_VER__ , 		32
db "COMPILING_MACHINE:",	COMPILING_MACHINE, 	32
db "COMPILING_OS:",		COMPILING_OS, 		32
db "COMPILING_HOST:",		COMPILING_HOST,		32
db 0