//This code revieves 2 arguments as shown in below.
//This code translates a regular assembly file generated by gcc with -S -Mintel and -m32 options
//to raw assembly. The output file can bu compiled by nasm with -f bin option
//./asmEdit source.s raw.asm
//Author: Totan
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
